[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]
