[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = { version = "0.8.0", features = ["serde"] }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.204", default-features = false, features = [
    "derive",
] }
