[package]
name = "cpu_service"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.13"
common = { path = "../common" }
serialport = "4.5.0"
postcard = { version = "1.0.10", features = ["use-std"] }
